### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by SkyLeite** [KazeSenoue/pso2-matchmaking#1]
**\- Bugs and unintended stuff**
- [ ] Make #matchmaking commands only
- [x] Fix !changePID ""
- [x] Fix no nickname (when user's discord username is the same as their nickname)
- [ ] Fix !changePID "@everyone"
- [x] Fix !join logic (loop through entries looking for a match)
- [x] finishQuest still doesn't work 100% of the time

**\- Requested features**
- [ ] Ping when a group is almost full
- [ ] Ping @everyone in group when someone joins
- [ ] Better group board
- [ ] Voice calls
- [ ] Edit group

**\- System improvements**
- [x] Lock shit (Thanks @Zogzer)
- [x] Make !changePID also change owner / member name
- [ ] Delete commands once they're processed
- [ ] Ping every once in a while so groups don't just die
- [ ] Let group owners add ghost members
- [ ] Member board when group is created (pinned message on group channel)
